### ISSUE TITLE
[Wishlist] Mounting the Storage

### ISSUE THREAD

**Issue by MartinX3** [Streetwalrus/android_usb_msd#1]
It would be nice, if i could mount the storage, instead of an ISO-file.

MTP is pretty slow.

**Comment by toxtox** [comment]
YES @MartinX3 , some Cyanogenmod versions ago it was possible but unstable to mount your phone storage as "**_mass storage device_**" for writing and reading. 
The MTP support under LINUX is a very unstable and writing to the phone storage is not possible, only reading seems to be possible.
**Therefore mounting the complete phone storage directly would be very pleasant.**

**Comment by MartinX3** [comment]
MTP is stable in Linux Mint 18.1, but slow.
The advantage is, that you can use the SDCard, while mounting on your pc.

But i can live with a device on standby, while mounting the SDCard.

**Comment by Streetwalrus** [comment]
This is impossible to do without shutting Android down entirely, I can't do anything about it. SD cards are feasible but I don't have a device with an SD slot so I can't test it.

**Comment by MartinX3** [comment]
But the old sdcard mode worked very fine, even on phones without a sdcard.

**Comment by Streetwalrus** [comment]
That has nothing to do with file systems. Android uses ext4 on most devices, f2fs on some, and they are free to use for anything.

Old devices handled mounting to the PC by having a separate partition that was treated like an SD card, and unmounting it as necessary. Newer devices have a unified internal storage partition to which all your applications are installed, and all other settings Android relies on to run. The only way to unmount it is to stop the framework and take over, which is a huge undertaking and out of scope for this application.

**Comment by MartinX3** [comment]
Thank you
