### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by C0rn3j** [Streetwalrus/android_usb_msd#10]
Cool app, where's the donate info though? Or do you not need any donations?

**Comment by Streetwalrus** [comment]
I didn't think anyone would want to donate for this, so I've never added any details to the readme before. I have a PayPal button now, I might add a Bitcoin address eventually, I currently don't have a wallet set up.

**Comment by C0rn3j** [comment]
Hey, I can ditch DriveDroid for this and the license is at least MIT! That alone is worth a donation.

Would prefer a copyleft license and perhaps some more features, but that's not that important ^^

Paypal works for me, so thanks for adding the button.

**Comment by Streetwalrus** [comment]
You're welcome. :)

I usually prefer permissive licenses myself, though I might consider the MPL in the future.

I'll keep the issue open as a reminder to add a Bitcoin address because I want to have that as an option if I'm gonna accept donations anyway.

**Comment by Streetwalrus** [comment]
Added a BTC address to the README, need to add links to the F-Droid repo as well.
