### ISSUE TITLE
Reboot when trying to mount

### ISSUE THREAD

**Issue by mase76** [Streetwalrus/android_usb_msd#12]
Hi!
I get an immediate reboot when trying to mount an image. No chance to log. My system is omnirom 7.1.2 on a sony xperia x. Root access is granted.
It worked fine in the past on other devices with other roms. This is the first time I use omnirom.
Any idea how to examine this?

**Comment by Streetwalrus** [comment]
Wow, this sounds like hell. Please post your `/proc/kmsg` or `/sys/fs/pstore/console-ramoops-0` (depends on your device) after the crash.

**Comment by mase76** [comment]
Here is my kmsg, dmesg-ramoops-0 and dmesg-ramoops-1.
console-ramoops-0 does not exist on my system.
I renamed them to txt to upload them here.
[dmesg-ramoops-0.txt](https://github.com/Streetwalrus/android_usb_msd/files/1183223/dmesg-ramoops-0.txt)
[dmesg-ramoops-1.txt](https://github.com/Streetwalrus/android_usb_msd/files/1183225/dmesg-ramoops-1.txt)
[kmsg.txt](https://github.com/Streetwalrus/android_usb_msd/files/1183224/kmsg.txt)

**Comment by Streetwalrus** [comment]
Oh, I'm dumb. I really meant `last_kmsg`, not `ksmg` which is the active kernel log. And it looks like they renamed the pstore version again, heh. Anyway, thanks for posting these, I'll take a look.

**Comment by Streetwalrus** [comment]
Is your device officially supported by Omni ? I can't seem to find the sources for it on their GitHub. I'll need to take a look at the kernel sources to find what causes the crash.

**Comment by mase76** [comment]
My device is a Sony Xperia X (Suzu). It is officially supported.

**Comment by Streetwalrus** [comment]
Yeah, I've found the kernel sources. I'm gonna have to make you run tests later. Do you use Telegram or IRC? It'd be a little easier to debug this live.

**Comment by mase76** [comment]
xmpp or irc. Choose yours.

**Comment by Streetwalrus** [comment]
I'm on Efnet (Streetwal) and Freenode (Streetwalrus). PM me so we can find a moment to do it.

**Comment by mase76** [comment]
Seems that we missed each other. Do you still want to debug this?

**Comment by mase76** [comment]
Any news? I posted that issue in the Omnirom forum, but no replies yet.

**Comment by Streetwalrus** [comment]
I'm sorry, I've completely forgotten about this. My availability is getting worse now that uni is starting again and I have mostly lost interest in this project. If your ROM maintainers can't do anything for you, I doubt I'll be able to either.

**Comment by mase76** [comment]
Hi!
Today I got Omnirom 8.1.0 for my device. The device does not crash any more,
when using usbmountr.
The message for the mounted image appears, but the PC does not recognize
anything. I think, we can close this issue. Is the app known to work with Oreo?

**Comment by Streetwalrus** [comment]
I haven't tried Oreo yet due to lack of interest in the upgrade and time. The app is mostly kernel-dependent, so Oreo itself shouldn't make a big difference. The message is there to indicate that the script ran successfully but I can't guarantee anything beyond that.

**Comment by Streetwalrus** [comment]
The original issue is not a problem anymore. Considering #27 as the new issue.
