### ISSUE TITLE
Option to automatically switch to PTP

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [Streetwalrus/android_usb_msd#15]
On my Smartphone (Galaxy S5) this app only works when I switch to PTP. But if I want to boot a computer with this app, oftem I'm too slow in changing the Android USB settings to PTP and click mount on this app again so I cannot boot. An option to do this automatically would be great.

**Comment by Streetwalrus** [comment]
I'm not sure what kind of bullshit Samsung does, but you should ask your ROM maintainer to fix this.
