### ISSUE TITLE
[Question] Disk formatting

### ISSUE THREAD

**Issue by Kristinita** [Streetwalrus/android_usb_msd#16]
### 1. Briefly

I don't understand, is it safe to use USB Mountr.

#### 1. Smartphone

I can't find information, can I use my smartphone for USB Mountr usage.

+ ARK Benefit S401,
+ Android 5.1.1,
+ MicroSD 8GB,
+ USB Mountr 0.5 (latest F-Droid version at the moment).

#### 2. PC

+ Windows 10 Enterprise LTSB EN.

### 3. Steps to reproduce

I install USB Mountr via F-Droid → I restart smartphone → I open USB Mountr → I provided root for USB Mountr → I connect the smartphone to PC via USB → I press `Mount`.

Now I see the window:

> You need to format the disk in Drive G: before you can use it. Do you want to format it?

![Format](https://i.imgur.com/Y6UsOhu.png)

My Device Manager:

![Device manager](https://i.imgur.com/MQPpEtW.png)

In `Impress Ino` my Phone storage and MicroSD:

![Impress Ino](https://i.imgur.com/AkFxUiN.png)

### 4. Questions

1. Can I use USB Mountr for my smartphone?
1. If yes, do I have to format the drive G?
1. If yes, could this lead to any consequences for my phone? Yes, I understood, that I need to create backup data from my phone. But if I restore information, will this have any implications?

Thanks.

**Comment by Streetwalrus** [comment]
The whole "drive G" should be redirected to the file you pointed USB Mountr to. That file should be a valid disk image for your machine to recognize it properly. You can also create an empty file on the phone with the command `truncate -s 1G` for example, then mount it and format it.
What kind of file are you currently pointing it to?
