### ISSUE TITLE
Two drives get mounted

### ISSUE THREAD

**Issue by joserebelo** [Streetwalrus/android_usb_msd#25]
I'm running Android 8.1 (Cardinal-AOSP), and two drives get mounted for a single image. I'm guessing it has something to do with both  `$usb/f_mass_storage/lun` and `$usb/f_mass_storage/lun0` being used. Is there no way to check for the multiple lun support, like the existence of `$usb/f_mass_storage/luns`?

I'd be willing to implement it, I'm just not familiar enough with the system yet.

**Comment by Streetwalrus** [comment]
The assumption is that only one of those two should be present in a kernel. The former is the upstream code from Google, the latter is enabled by a CAF patch which supposedly removes the former, at least in my experience.

**Comment by Streetwalrus** [comment]
That's an option. This whole application was written in an afternoon and lazily tested on two devices, I went with what worked on both. I'll look into this later, very busy with other projects currently and this is pretty low priority for me.

**Comment by Exaeta** [comment]
I have this bug too.

@Streetwalrus This app seems like it could be really useful, but the automount feature can cause image corruption (if not mounted in the read only mode). If you fix it I'll give you a $100 bounty via paypal/bitcoin. :)

If possible, can we also set the device name to something other than "Linux File-CD Gadget"? Being able to set the name in the UI would be nice.

**Comment by Streetwalrus** [comment]
By automount, do you mean the host is mounting the image twice because of this?

**Comment by Streetwalrus** [comment]
@joserebelo @Exaeta I've published a new release, can you build it (or wait until F-Droid picks it up) and report back?

**Comment by Streetwalrus** [comment]
You can also try [https://wank.party/IIMT.apk](this APK) which I've built and signed with my own release key (intentionally not putting this one on the releases page).

**Comment by joserebelo** [comment]
@Streetwalrus can confirm, it now only mounts a single drive :)

**Comment by Exaeta** [comment]
@Streetwalrus This half fixed it. Two devices show up, but only one actually works and can be mounted. The other shows up but has a size of 0 and can't be mounted. I guess this counts?

**Comment by Streetwalrus** [comment]
In this case the remaining bit is a bug in your kernel and there isn't much I can do about it, so this is fixed as far as I'm concerned.
