### ISSUE TITLE
Root access denied on un-/mount

### ISSUE THREAD

**Issue by schulmar** [Streetwalrus/android_usb_msd#29]
I run USB Mountr (version 0.6 from F-Droid) on Lineage OS 14.1-20171101-Nightly-i9300 (Android 7.1.2) on a Samsung Galaxy S3.
After selecting an .iso image, trying to mount gives following error:

> Root-Zugriff verweigert

Which translates to

> Root access denied

How to proceed?

**Comment by Streetwalrus** [comment]
Make sure your device is properly rooted. For LineageOS, you need to download the add-on package from their website, and enable root access for apps in developer settings. Once that is set up properly, you should be prompted to allow root access for the app.

**Comment by martin-schulze-vireso** [comment]
You are right. After rooting it correctly, I could mount without problems. Unfortunately, booting did not work. The mount seems to be turned off, when the computer tries to connect.

**Comment by Streetwalrus** [comment]
Some kernels are kinda wonky and sometimes Android will mess with it as well. Make sure you enable the mount while a proper USB data connection to a computer is established. Please open a new issue for any further questions.
