### ISSUE TITLE
Hard reboots phone when mounting ISO

### ISSUE THREAD

**Issue by parkerlreed** [Streetwalrus/android_usb_msd#30]
Nexus 6P 8.1 Oreo

Magisk v16

Selected Arch Linux ISO and every time I hit mount, the phone locks up and fully reboots

**Comment by Streetwalrus** [comment]
Are you running the stock rom? Also note that I won't support Magisk because of the way it screws with the system. Please try with regular root (yes, the one that modifies your system partition). If you can still reproduce that way, we can try further troubleshooting.

**Comment by parkerlreed** [comment]
Yeah stock. Magisk is really the most common way nowadays. SuperSU and the like can't be trusted. If it's not working due to that, then I guess I won't use this software. Thanks.

**Comment by Streetwalrus** [comment]
Sorry, I can't help then. If anyone is able to reproduce this without magisk, I can reopen this and check things out with you.
