### ISSUE TITLE
MTP is completely broken

### ISSUE THREAD

**Issue by floppyD** [Streetwalrus/android_usb_msd#39]
I was running Lineage 14.1 on a Moto G3 (osprey) and tried your app, and it didn't only not work but completely broke MTP. It just doesn't work anymore, and USB behaves really weirdly now, when I plug the phone on my PC it does nothing, doesn't even show the charge/mtp/ptp notification. And the most weird thing, if I plug the cable on the computer, disconnect and try to use a charger, it won't work until the next reboot. And another thing, MTP doesn't work even on TWRP. I already tried everything, uninstalling the app, adb (it doesn't work), trying some commands through the terminal, formatting and reflashing the ROM, flashing the stock ROM and even flashing a stock firmware, but nothing worked so far. The only USB input I can get from my PC is fastboot, so I'm guessing there's something serious going on. Do you have any idea of what's happening and how can I fix it?

**Comment by Streetwalrus** [comment]
I don't know, you should take this to your Lineage and TWRP maintainers. This application touches nothing that should do permanent damage. Since USB works in fastboot mode, your device is definitely not broken.
